package com.revature.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-09T10:49:16.747-04:00
 * Generated source version: 3.3.0
 *
 */
@WebService(targetNamespace = "http://ws.revature.com/", name = "ArticleService")
@XmlSeeAlso({ObjectFactory.class})
public interface ArticleService {

    @WebMethod
    @RequestWrapper(localName = "deleteArticle", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DeleteArticle")
    @ResponseWrapper(localName = "deleteArticleResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.DeleteArticleResponse")
    public void deleteArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Article arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getArticlesByTitle", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetArticlesByTitle")
    @ResponseWrapper(localName = "getArticlesByTitleResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetArticlesByTitleResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.revature.ws.Article> getArticlesByTitle(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "addArticle", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.AddArticle")
    @ResponseWrapper(localName = "addArticleResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.AddArticleResponse")
    public void addArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        com.revature.ws.Article arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getAllArticles", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllArticles")
    @ResponseWrapper(localName = "getAllArticlesResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.GetAllArticlesResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.util.List<com.revature.ws.Article> getAllArticles();

    @WebMethod
    @RequestWrapper(localName = "updateArticle", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdateArticle")
    @ResponseWrapper(localName = "updateArticleResponse", targetNamespace = "http://ws.revature.com/", className = "com.revature.ws.UpdateArticleResponse")
    public void updateArticle(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        java.lang.String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        java.lang.String arg2
    );
}
