
package com.revature.ws;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-09T10:49:16.686-04:00
 * Generated source version: 3.3.0
 *
 */
public final class ArticleService_ArticleServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://ws.revature.com/", "ArticleServiceImplService");

    private ArticleService_ArticleServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ArticleServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        ArticleServiceImplService ss = new ArticleServiceImplService(wsdlURL, SERVICE_NAME);
        ArticleService port = ss.getArticleServiceImplPort();

        {
        System.out.println("Invoking deleteArticle...");
        com.revature.ws.Article _deleteArticle_arg0 = new com.revature.ws.Article();
        port.deleteArticle(_deleteArticle_arg0);


        }
        {
        System.out.println("Invoking getArticlesByTitle...");
        java.lang.String _getArticlesByTitle_arg0 = "";
        java.util.List<com.revature.ws.Article> _getArticlesByTitle__return = port.getArticlesByTitle(_getArticlesByTitle_arg0);
        System.out.println("getArticlesByTitle.result=" + _getArticlesByTitle__return);


        }
        {
        System.out.println("Invoking addArticle...");
        com.revature.ws.Article _addArticle_arg0 = new com.revature.ws.Article();
        port.addArticle(_addArticle_arg0);


        }
        {
        System.out.println("Invoking getAllArticles...");
        java.util.List<com.revature.ws.Article> _getAllArticles__return = port.getAllArticles();
        System.out.println("getAllArticles.result=" + _getAllArticles__return);


        }
        {
        System.out.println("Invoking updateArticle...");
        int _updateArticle_arg0 = 0;
        java.lang.String _updateArticle_arg1 = "";
        java.lang.String _updateArticle_arg2 = "";
        port.updateArticle(_updateArticle_arg0, _updateArticle_arg1, _updateArticle_arg2);


        }

        System.exit(0);
    }

}
