package com.revature.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.3.0
 * 2021-04-09T10:49:16.757-04:00
 * Generated source version: 3.3.0
 *
 */
@WebServiceClient(name = "ArticleServiceImplService",
                  wsdlLocation = "http://localhost:8080/BlogForm/soap/article?wsdl",
                  targetNamespace = "http://ws.revature.com/")
public class ArticleServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.revature.com/", "ArticleServiceImplService");
    public final static QName ArticleServiceImplPort = new QName("http://ws.revature.com/", "ArticleServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8080/BlogForm/soap/article?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ArticleServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8080/BlogForm/soap/article?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ArticleServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ArticleServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ArticleServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ArticleServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ArticleServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ArticleServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns ArticleService
     */
    @WebEndpoint(name = "ArticleServiceImplPort")
    public ArticleService getArticleServiceImplPort() {
        return super.getPort(ArticleServiceImplPort, ArticleService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ArticleService
     */
    @WebEndpoint(name = "ArticleServiceImplPort")
    public ArticleService getArticleServiceImplPort(WebServiceFeature... features) {
        return super.getPort(ArticleServiceImplPort, ArticleService.class, features);
    }

}
